version: '3.1'
services:
  itoken-zipkin:
    restart: always
    image: 192.168.219.149:5000/itoken-zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_networks

networks:
  zipkin_networks: